:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Terraform vs CloudFormation
Ron Kurr <rkurr@jvmguy.com>


toc::[]

== Overview
This is a very unscientific comparison between https://www.terraform.io/[Terraform] and https://aws.amazon.com/cloudformation/[AWS CloudFormation].  What we'll do is to implement a couple tasks in both tools and evaluate their strengths and weaknesses.

=== Tagging
Resource tagging is very important in AWS so we'll apply a common set of tags to all resources, calling out any differences in tagging support.

=== VPC Creation
The first task is to create a new VPC that contains a public and private subnet for each availability zone in the region.

=== Bastion Box
SSH access must be done by proxying through a Bastion server.  Install a single EC2 instance of type t2.nano, restricting access to port 22 from a single ip address.  Create an autoscaling group that will ensure we always have at least one box up and running.  The autoscaling group should be configured to turn off the boxes after normal business hours.

=== ECS Cluster
Create an ECS cluster using Spot Instances of type M4.large.  Install it into the private subnets.

=== Deploy An ECS Service
Deploy a container so that each node in the cluster gets one instance.

=== Update The ECS Service
Update a new version of the container with different environment values.

TIP: foo

IMPORTANT: bar

== Prerequisites

* an https://aws.amazon.com/[AWS] account
* an SSH client
* familiarity with https://aws.amazon.com/ec2/[EC2]

== Building

== Installation

== Tips and Tricks

== Troubleshooting

== Comparison
=== VPC Creation
Creating a VCP between the two tools is fairly similar.  Each makes you describe the various building blocks needed to construct a fully functional VPC and assemble them as needed.  Where they do differ is in the handling multiple instances of the same object.  For example, the scenario is to place  subnets into all availability zones of the region.  The Virgina region has 6 AZs while the Ohio region only has 3.  Terraform has a construct that allows you to build the same resource N number of times, saving on duplicated code.  CloudFormation does not provide anything similar so you have to duplicate the directives, increasing the amount of code and making the script less reusable.

NOTE: It has been awhile since I've scoured through the CloudFormation documentation looking for a "loop" construct but I suspect it still doesn't exist because the https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/ECS/EC2LaunchType/clusters/public-vpc.yml[AWS Samples] still repeat declarations for each subnet.

Another minor difference is that Terraform is command-line only while CloudFormation is GUI based.  Depending on the operator, this may be a differentiator.

NOTE: CloudFormation does have a command-line but it simply kicks off the process, requiring you to then monitor the job in the console.

Compare the source of the link:terraform/vpc/main.tf[Terraform version] to the link:cloudformation/vpc/vpc.yml[CloudFormation version] and see which you prefer.

== License and Credits
This project is licensed under the https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].
