---
AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates the full stack of services created piece meal in the other modules.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this stack is being created for'
        Type: 'String'
        Default: 'Bake Off'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'Show casing the differences between CloudFormation and Terraform.'

#### VPC stuff
    VpcURL:
        Description: 'Location of the VPC template file'
        Type: 'String'
        Default: 'https://s3.us-east-2.amazonaws.com/com-jvmguy-cloudformation-templates/vpc/vpc.yml'

    VpcName:
        Description: 'Name of the VPC'
        Type: 'String'
        Default: 'Bake Off'

    SshKeyName:
        Description: 'Name of the key to use when creating the EC2 instances'
        Type: 'String'
        Default: 'BakeOff'

    Network:
        Description: 'The ip range to use when building out the VPC network'
        Type: 'String'
        Default: '10.0.0.0'

#### Bastion stuff
    BastionURL:
        Description: 'Location of the Bastion template file'
        Type: 'String'
        Default: 'https://s3.us-east-2.amazonaws.com/com-jvmguy-cloudformation-templates/bastion/bastion.yml'

    SshKeyName:
        Description: 'Name of the key to use when creating the EC2 instances'
        Type: 'AWS::EC2::KeyPair::KeyName'
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
        Default: 'BakeOff'

    SshCidr:
        Description: 'IP range, in CIDR notation, that is allowed to SSH into the Bastion'
        Type: 'String'
        Default: '50.235.141.198/32'

    ScaleUpExpression:
        Description: 'Cron expression indicating when instances should be spun up.'
        Type: 'String'
        Default: '0 7 * * MON-FRI'

    ScaleDownExpression:
        Description: 'Cron expression indicating when instances should be spun down.'
        Type: 'String'
        Default: '0 0 * * SUN-SAT'

Resources:
    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: VpcURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                Name:
                    Ref: VpcName

    Bastion:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: BastionURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName
                SshCidr:
                    Ref: SshCidr
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                PublicSubnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.PublicSubnets
                ScaleUpExpression:
                    Ref: ScaleUpExpression
                ScaleDownExpression:
                    Ref: ScaleDownExpression
